name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release:
    name: Build binaries and create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dart-lang/setup-dart@v1

      - run: dart pub get

      - run: dart run build_runner build --delete-conflicting-outputs

      - name: Compile for Linux
        run: |
          dart compile exe bin/replace.dart -o replace --target-os=linux
          dart compile exe bin/pm.dart -o pm --target-os=linux

      - if: github.event_name != 'workflow_dispatch'
        uses: softprops/action-gh-release@v3
        with:
          files: |
            replace
            pm

  publish:
    name: Publish to pub.dev
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dart-lang/setup-dart@v1

      - run: |
          dart pub get
          dart pub publish --force